modules/Stsbl/BillBoardBundle/Entity/Entry.php
<?php

declare(strict_types=1);

namespace Stsbl\BillBoardBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use IServ\CoreBundle\Entity\User;
use IServ\CrudBundle\Entity\CrudInterface;
use IServ\Library\Zeit\Zeit;
use Symfony\Component\Validator\Constraints as Assert;

/*
 * The MIT License
 *
 * Copyright 2021 Felix Jacobi.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

/**
 * @author Felix Jacobi <felix.jacobi@stsbl.de>
 * @license MIT license <https://opensource.org/licenses/MIT>
 *
 * @ORM\Entity
 * @ORM\Table(name="billboard")
 * @ORM\HasLifecycleCallbacks
 */
class Entry implements CrudInterface
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private ?int $id;

    /**
     * @ORM\Column(name="title", type="text")
     * @Assert\NotBlank()
     */
    private ?string $title;

    /**
     * @ORM\Column(name="description", type="text")
     * @Assert\NotBlank()
     */
    private ?string $description;

    /**
     * @ORM\Column(name="time", type="datetimetz_immutable", nullable=false)
     */
    private \DateTimeImmutable $time;

    /**
     * @ORM\Column(name="updated_at",type="datetimetz_immutable",nullable=false)
     */
    private \DateTimeImmutable $updatedAt;

    /**
     * @ORM\ManyToOne(targetEntity="\Stsbl\BillBoardBundle\Entity\Category", fetch="EAGER")
     * @ORM\JoinColumn(name="category", referencedColumnName="id")
     * @Assert\NotNull()
     */
    private ?Category $category;

    /**
     * @ORM\ManyToOne(targetEntity="\IServ\CoreBundle\Entity\User", fetch="EAGER")
     * @ORM\JoinColumn(name="author", referencedColumnName="act")
     */
    private ?User $author;

    /**
     * @ORM\Column(name="visible", type="boolean")
     */
    private bool $visible = true;

    /**
     * @ORM\Column(name="closed", type="boolean")
     */
    private bool $closed = false;

    /**
     * @ORM\OneToMany(targetEntity="EntryImage", mappedBy="entry")
     *
     * @var Collection&EntryImage[]
     */
    private Collection $images;

    /**
     * @ORM\OneToMany(targetEntity="EntryComment", mappedBy="entry")
     *
     * @var Collection&EntryComment[]
     */
    private Collection $comments;

    /**
     * The constructor
     */
    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->time = Zeit::now();
        $this->updatedAt = Zeit::now();
    }


    /**
     * Lifecycle callback to set the update date
     *
     * @ORM\PreUpdate
     */
    public function onUpdate(): void
    {
        $this->updateLastUpdatedTime();
    }

    /**
     * Updates last updated time to 'now'
     */
    public function updateLastUpdatedTime(): void
    {
        $this->setUpdatedAt(Zeit::now());
    }

    /**
     * {@inheritdoc}
     */
    public function __toString(): string
    {
        return $this->title ?? '?';
    }

    /**
     * {@inheritdoc}
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function getTime(): ?\DateTimeImmutable
    {
        return $this->time;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function isVisible(): bool
    {
        return $this->visible;
    }

    /**
     * @return Collection&EntryImage[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    /**
     * @return Collection&EntryComment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    /**
     * @return $this
     */
    public function setTitle(string $title = null): self
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return $this
     */
    public function setDescription(string $description = null): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return $this
     */
    public function setTime(\DateTimeImmutable $time): self
    {
        $this->time = $time;

        return $this;
    }

    /**
     * @return $this
     */
    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return $this
     */
    public function setCategory(Category $category = null): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return $this
     */
    public function setAuthor(User $author = null): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return $this
     */
    public function setVisible(bool $visible): self
    {
        $this->visible = $visible;

        return $this;
    }

    /**
     * Checks if the author is valid. i.e. he isn't deleted.
     */
    public function hasValidAuthor(): bool
    {
        return $this->author !== null;
    }

    /**
     * Returns a displayable author. Performs an exists check.
     */
    public function getAuthorDisplay(): string
    {
        return $this->hasValidAuthor() ? (string)$this->getAuthor() : '?';
    }

    /**
     * @return $this
     */
    public function setClosed(bool $closed): self
    {
        $this->closed = $closed;

        return $this;
    }

    public function isClosed(): bool
    {
        return $this->closed;
    }

    /**
     * @return $this
     */
    public function addImage(EntryImage $image): self
    {
        $this->images[] = $image;

        return $this;
    }

    /**
     * @return $this
     */
    public function removeImage(EntryImage $image): self
    {
        $this->images->removeElement($image);

        return $this;
    }

    public function hasImage(EntryImage $image): bool
    {
        return $this->images->contains($image);
    }

    /**
     * @return $this
     */
    public function addComment(EntryComment $comment): self
    {
        $this->comments[] = $comment;

        return $this;
    }

    /**
     * @return $this
     */
    public function removeComment(EntryComment $comment): self
    {
        $this->comments->removeElement($comment);

        return $this;
    }

    public function hasComment(EntryComment $comment): bool
    {
        return $this->comments->contains($comment);
    }
}

modules/Stsbl/BillBoardBundle/Resources/views/Crud/entry_add.html.twig
{% extends '@IServCrud/Crud/add.html.twig' %}

{% block content %}
    {% if fields is empty %}
        <div class="alert alert-warning">
            {{ _("There are no bill-board categories configured yet. Please contact your administrator.") }}
        </div>
    {% else %}
        {% if rules is not empty %}
            <div class="alert alert-info">
                <p><strong> {{ _("Rules for posting on the Bill-Board:") }}</strong></p>
                <p>{{ rules | nl2br }}</p>
            </div>
        {% endif %}
        {{ parent() }}
    {% endif %}
{% endblock %}

{% block javascripts %}
    {{ parent() }}

    {% if app.environment != 'prod' %}
        <!-- {{ _self }} => TinyMCE -->
    {% endif %}
    <script type="text/javascript" src="{{ asset('js/tinymce5.js', 'vendor') }}"></script>
    {% if app.request.locale == 'de_DE' %}
        <script type="text/javascript" src="{{ asset('js/tinymce5-de.js', 'vendor') }}"></script>
    {% endif %}
    
    {% if app.environment != 'prod' %}
	<!-- {{ _self }} => editor.js -->
    {% endif %}
    <script src="{{ asset('js/editor.js', 'stsbl_bill_board') }}"></script>
{% endblock %}

modules/Stsbl/BillBoardBundle/Resources/views/Crud/entry_edit.html.twig
{% extends '@IServCrud/Crud/edit.html.twig' %}

{% block content %}
    {% if fields is empty %}
        <div class="alert alert-warning">
            {{ _("There are no bill-board categories configured yet. Please contact your administrator.") }}
        </div>
    {% else %}
        {% if rules is not empty %}
            <div class="alert alert-info">
                <p><strong> {{ _("Rules for posting on the Bill-Board:") }}</strong></p>
                <p>{{ rules | nl2br }}</p>
            </div>
        {% endif %}
        {{ parent() }}
    {% endif %}
{% endblock %}

{% block javascripts %}
    {{ parent() }}

    {% if app.environment != 'prod' %}
        <!-- {{ _self }} => TinyMCE -->
    {% endif %}
    <script type="text/javascript" src="{{ asset('js/tinymce5.js', 'vendor') }}"></script>
    {% if app.request.locale == 'de_DE' %}
        <script type="text/javascript" src="{{ asset('js/tinymce5-de.js', 'vendor') }}"></script>
    {% endif %}

    {% if app.environment != 'prod' %}
        <!-- {{ _self }} => editor.js -->
    {% endif %}
    <script src="{{ asset('js/editor.js', 'stsbl_bill_board') }}"></script>
{% endblock %}

modules/Stsbl/BillBoardBundle/Resources/views/Crud/entry_index.html.twig
{% extends '@IServCrud/Crud/index.html.twig' %}
{% import '@IServCrud/macros.html.twig' as m %}

{% block content %}
    {% if is_granted(constant('\\Stsbl\\BillBoardBundle\\Security\\Privilege::BILLBOARD_MANAGE')) %}
        <div class="btn-toolbar pull-right">
            {{ m.linkButton(path('manage_billboard'), _('Manage'), 'cog', 'btn-link') }}
        </div>
    {% endif %}
    {{ parent() }}
{% endblock %}

modules/Stsbl/BillBoardBundle/Resources/views/Crud/entry_show.html.twig
{% extends '@IServCrud/Crud/show.html.twig' %}

{% block content %}
    <h1>{{ item.title }}</h1>
    {% block crud_form_actions %}
        {{ parent() }}
    {% endblock %}
    
    {% block crud_show %}
        <div class="panel panel-default">
            <div class="panel-body">
                <p class="text-secondary">
                    <span title="{{ _('Created') }}">{{ icon('calendar') }} {{ item.time|ldate }}</span> | 
                    <span title="{{ _('Last refresh') }}">{{ icon('refresh') }} {{ item.updatedAt|ldate }}</span> | 
                    <span title="{{ _('Author') }}">
                        {{ icon('user') }}
                        {% if not authorIsDeleted %}
                            <a>{{ item.author|mailto({'addressee': item.author, 'subject': __('Entry "%s" on the billboard', item.title)}) }}</a>
                        {% else %}
                            {{ item.authorDisplay }}
                        {% endif %}
                    </span> | 
                    <span title="{{ _('Category') }}">{{ icon('tag') }} {{ item.category }}</span> | 
                    <span title="{{ _('Visibility') }}">
                        {% if item.visible %}
                            {{ icon('eye-open') }} {{ _('Visible') }}
                        {% else %}
                            {{ icon('eye-close') }} {{ _('Hidden') }}
                        {% endif %}
                    </span>
                    {% if item.closed %}
                        | <span title="{{ _('This entry is closed for any write access.') }}">{{ icon('lock') }} {{ _p('billboard', 'Closed') }}</span>
                    {% endif %}
                </p>

                <p>
                    {{ item.description|raw|linkify }}
                </p>
            </div>
        </div>
    {% endblock crud_show %}
    {% block entry_images %}
        {% if item.images|length > 0 or admin.isAuthor(item) %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">{{ _('Images') }}</h3>
                </div>
                <div class="panel-body">
                    {% set thumbsize = thumbsize|default(80) %}
                    {% set images = item.images %}
                    {% if images is iterable and images|length > 0 %}
                        {% for ent in images %}
                            {% apply spaceless %}
                                <div class="billboard-image-container">
                                {% set imageRoute = 'billboard_fileimage_image' %}
                                <a data-toggle="modal-image" href="{{ path(imageRoute, {'id': ent.id, 'entityId': item.id}) }}">
                                    <img src="{{ path(imageRoute, {'id': ent.id, 'entityId': item.id, 'width': thumbsize, 'height': thumbsize}) }}"
                                    alt="{{ ent }}" class="img-thumbnail" width="{{ thumbsize }}" height="{{ thumbsize }}"/>
                                </a>
                                <br />
                                {% if ent.description|length > 0 %}
                                    <span class="text-muted text-secondary"><strong>{{ _('Description')}}:</strong><br />{{ ent.description }}</span>
                                {% endif %}
                                
                                {% if admin.isAllowedToEdit(item, app.user) %}
                                    <br />
                                    <a href="#delete-image" id="billboard-delete-image-{{ ent.id }}" data-id="#billboard-delete-image-{{ ent.id }}" data-image-name="{{ ent.imageName }}" data-image-entry-title="{{ ent.entry.title }}" data-image-id="{{ ent.id }}" data-toggle="modal" data-target="#image-delete-confirm-container" class="billboard-delete-image btn btn-xs btn-default">{{ icon('remove-circle') }}{{ _('Delete') }}</a>
                                {% endif %}
                                </div>
                            {% endapply %}
                        {% endfor %}
                    {% elseif images is iterable and images|length == 0 %}
                        {% if item.closed and not admin.isModerator(app.user) %}
                            <span class="text-muted">{{ _('You can not add further images to this entry, because it is closed.') }}</span>
                        {% else %}
                            <span class="text-muted">{{  _('This entry currently has no images. To add one, click "Add image" below.') }}</span>
                        {% endif %}
                    {% endif %}
                </div>
                <div class="panel-footer">
                    {% if admin.isAuthor(item) and (not item.closed or admin.isModerator(app.user)) %}
                        <div class="billboard-clear-both"></div>
                        <a href="#billboard-add-image" id="billboard-add-image" data-id="billboard-add-image" data-toggle="modal" data-target="#image-upload-container" class="btn-default btn">{{ icon('plus') }}{{ _('Add image') }}</a>
                    {% endif %}
                </div>    
            </div>
        {% endif %}
    {% endblock %}
    
    {% block entry_comments %}
        <h2>{{ _p('billboard', 'Comments') }}</h2>
        {% if item.comments is empty %}
            <div class="panel panel-default">
                <div class="panel-body">
                    {{ _('Currently no comments.') }}
                </div>
            </div>
        {% else %}
            {% for comment in item.comments %}
                <div id="billboard-comment-{{ comment.id }}" class="panel panel-default">
                    <div class="panel-heading">
                        <strong>{{ comment.title }}</strong> {{ ' ' ~ _("by") ~ ' ' }} {{ icon('user') }}  {{ __("%s at %s", comment.authorDisplay, comment.time|ldatetime) }} <br />
                    </div>
                    <div class="panel-body">
                        {{ comment.content|linkify }}
                    </div>
                    {% if admin.isModerator(app.user) %}
                        <div class="panel-footer">
                            <a class="btn btn-default" href="{{ path('billboard_comment_delete_confirm', {'id': comment.id}) }}">{{ icon('remove-circle') }}{{ _('Delete') }}</a>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        {% endif %}
    {% endblock %} 
    {% block entry_add_comment %}
        {% if admin.isAllowedToAdd(app.user) %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">{{ _('Add a comment') }}</h3>
                </div>
                <div class="panel-body">
                    {% if not admin.isModerator(app.user) and item.closed %}
                        <div class="panel panel-default">
                            <div class="panel-body">
                                {{ _('This entry is locked, therefor the creation of comments is not longer possible.') }}
                            </div>
                        </div>
                    {% elseif commentsEnabled and admin.isAllowedToAdd(app.user) %}
                        {{ form(commentForm, {'style': null}) }}
                    {% else %}
                        <div class="panel panel-default">
                            <div class="panel-body">
                                {{ _('The adding of new comments was disabled by your administrator.') }}
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        {% endif %}
    {% endblock  %}
    {% block entry_modal_image_upload %}
    {% if admin.isAuthor(item) and (not item.closed or admin.isModerator(app.user)) %}
    <div id="image-upload-container" class="modal fade in" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content -->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">{{ _('Add a new image to this entry') }}</h4>
                </div>
                <div class="modal-body">
                    <p>{{ _("Upload a new image.") }}</p>
                    {{ form(imageUploadForm, { 'style': 'inline', 'attr': { 'id': 'image-upload' } }) }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">{{ icon('remove') }} {{ _('Close') }}</button>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    {% endblock %}
    {% block entry_modal_image_delete_confirm %}
        {% if admin.isAllowedToEdit(item, app.user) %}
            <div id="image-delete-confirm-container" class="modal fade in" role="dialog">
                <div class="modal-dialog">
                    <!-- Modal content -->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">{{ _('Delete image') }}</h4>
                        </div>
                        <div class="modal-body">
                            <p id="image-delete-confirm-question">{{ _p("billboard", "Do you really want to delete the image?") }}</p>
                            {{ form(imageDeleteConfirmForm, { 'style': 'inline', 'attr': { 'id': 'image-delete-confirm' } }) }}
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endblock %}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}

    {% if app.environment != 'prod' %}
        <!-- {{ _self }} => billboard.less -->
    {% endif %}
    <link rel="stylesheet" href="{{ asset('css/billboard.css', 'stsbl_bill_board') }}" />
{% endblock %}

{% block javascripts %}
    {{ parent () }}

    {% if app.environment != 'prod' %}
        <!-- {{ _self }} => image.js -->
    {% endif %}
    <script src="{{ asset('js/image.js', 'stsbl_bill_board') }}"></script>
{% endblock %}